puts "ciao"

users = [
{ :name => 'Andrew Hill', :email => 'andrew.hill@5rooms.com'},
{ :name => 'Wageng Monageng', :email => 'andrew.monageng@aiaccelerator.com'},
{ :name => 'Anel Malan', :email => 'anel.malan@5rooms.com'},
{ :name => 'Angelis Cupido', :email => 'angelis.cupido@aiaccelerator.com'},
{ :name => 'Anje Hoogervorst', :email => 'anje@aiaccelerator.com'},
{ :name => 'Ashley Marshall', :email => 'ashley.marshall@5rooms.com'},
{ :name => 'Avela ', :email => 'avela.bolilitye@aiaccelerator.com'},
{ :name => 'Avron Williams', :email => 'avron.williams@aiaccelerator.com'},
{ :name => 'Barry Greyvenstein', :email => 'barry.greyvenstein@5rooms.com'},
{ :name => 'Bianca  Sweetman', :email => 'bianca.sweetman@aiaccelerator.com '},
{ :name => 'Blamo Brooks', :email => 'blamo.brooks@5rooms.com'},
{ :name => 'Bruce Holmes', :email => 'bruce@aiaccelerator.com'},
{ :name => 'Candice Nefdt', :email => 'candice.nefdt@5rooms.com'},
{ :name => 'Carly Wilson', :email => 'carly.wilson@style36.co.za '},
{ :name => 'Carmen Lotter', :email => 'carmen.lotter@style36.co.za'},
{ :name => 'Cecil Benjamin', :email => 'cecil.benjamin@5rooms.com'},
{ :name => 'Charde Lambert', :email => 'charde.lambert@style36.com'},
{ :name => 'Charmaine Lodewyk', :email => 'charmaine.lodewyk@style36.co.za'},
{ :name => 'Chrismari Janse van Rensburg', :email => 'chrismari@aiaccelerator.com'},
{ :name => 'Christelle Vorster', :email => 'christelle.vorster@style36.co.za'},
{ :name => 'Claudia Daniels', :email => 'claudia.daniels@5rooms.com'},
{ :name => 'Colin Kitt', :email => 'colin.kitt@style36.co.za'},
{ :name => 'Lungiswa Nyatyowa', :email => 'colin.vonberg@aiaccelerator.com'},
{ :name => 'Colin Von Berg', :email => 'colin.vonberg@aiaccelerator.com'},
{ :name => 'Cornel Gordon', :email => 'cornel.gordon@5rooms.com'},
{ :name => 'Danielle Solomon', :email => 'danielle.solomon@style36.co.za'},
{ :name => 'Dorothea Solomon', :email => 'dorothea.solomon@aiaccelerator.com'},
{ :name => 'Dwight Geldenhuys', :email => 'dwight.geldenhuys@5rooms.com'},
{ :name => 'Eckart Mostert', :email => 'eckart.mostert@style36.co.za'},
{ :name => 'Eddie Mabushe', :email => 'eddie.mabushe@aiaccelerator.com'},
{ :name => 'Edmore Waruma', :email => 'eddie.waruma@5rooms.com'},
{ :name => 'Eduane Roos', :email => 'eduan.roos@aiaccelerator.com'},
{ :name => 'Elizabeth Abrahams', :email => 'elizabeth.abrahams@5rooms.com'},
{ :name => 'Emile Naude', :email => 'emile.naude@5rooms.com'},
{ :name => 'Emilian Popa', :email => 'emilian.popa@5rooms.com'},
{ :name => 'Erin Sallie', :email => 'erin.sallie@style36.co.za'},
{ :name => 'Eshaam Rabaney', :email => 'eshaam.rabaney@5rooms.com'},
{ :name => 'Ezile Qoboka', :email => 'ezile.qoboka@aiaccelerator.com'},
{ :name => 'Fadhl Manuel', :email => 'fadhl@aiaccelerator.com'},
{ :name => 'Farzaana Khan', :email => 'Farzaana.khan@kinderelo.co.za'},
{ :name => 'Farzana Congo', :email => 'farzana.congo@kinderelo.co.za'},
{ :name => 'Fiona Jewson', :email => 'fiona.jewson@5rooms.com'},
{ :name => 'Flavio Bezeccherri', :email => 'flavio@5rooms.com'},
{ :name => 'Francesca Berta', :email => 'francesca@aiaccelerator.com'},
{ :name => 'Gabbrielle Kannemeyer', :email => 'gabbi.kannemeyer@style36.co.za'},
{ :name => 'George Wyngaardt', :email => 'george@aiaccelerator.com'},
{ :name => 'Gillian Bowen', :email => 'gill@kinderelo.co.za'},
{ :name => 'Giselle Esau', :email => 'giselle@aiaccelerator.com'},
{ :name => 'Glen Furlong', :email => 'glen.furlong@5rooms.com'},
{ :name => 'Greg Docherty', :email => 'greg@aiaccelerator.com'},
{ :name => 'Guiddo Gray', :email => 'guiddo.gray@5rooms.com'},
{ :name => 'Gurshwin Gabriel', :email => 'gurshwin.gabriel@aiaccelerator.com'},
{ :name => 'Handre Oosthuizen', :email => 'handre.oosthuizen@aiaccelerator.com'},
{ :name => 'Haresh Rama', :email => 'haresh@aiaccelerator.com'},
{ :name => 'Hildegarde Human', :email => 'hildegarde.human@style36.co.za'},
{ :name => 'Hope Kester', :email => 'hope.kester@style36.co.za'},
{ :name => 'Imraan Appleby', :email => 'imraan.appleby@5rooms.com'},
{ :name => 'Iolanda Veltri', :email => 'iolanda@style36.co.za'},
{ :name => 'Irene Meloni', :email => 'irene.meloni@aiaccelerator.com'},
{ :name => 'Jacqueline Davids', :email => 'jacqueline@aiaccelerator.com'},
{ :name => 'Jake Cooper', :email => 'jake.cooper@aiaccelerator.com'},
{ :name => 'Janice Van Wyk', :email => 'janice.vanwyk@5rooms.com'},
{ :name => 'Jason Petersen', :email => 'jason.petersen@style36.co.za '},
{ :name => 'Jayde Robinson', :email => 'jayd.robinson@aiaccelerator.com'},
{ :name => 'Jayesh Mitha', :email => 'jayesh.mitha@5rooms.com'},
{ :name => 'Jean-Lee Adams', :email => 'jean@aiaccelerator.com'},
{ :name => 'Jeanne Schmulian', :email => 'jeanne.schmulian@5rooms.com'},
{ :name => 'Jeannine Klein', :email => 'jeannine@aiaccelerator.com'},
{ :name => 'Jo-Anne Stafford', :email => 'jo-anne.stafford@5rooms.com'},
{ :name => 'Jocelyn Wang', :email => 'jocelyn.wang@5rooms.com'},
{ :name => 'John Clark', :email => 'john.clark@5rooms.com'},
{ :name => 'John Hobanye', :email => 'john.hobyane@5rooms.com'},
{ :name => 'Jonell Janse van Rensburg', :email => 'jonell@aiaccelerator.com'},
{ :name => 'Joshua Siame', :email => 'joshua@aiaccelerator.com'},
{ :name => 'Julie-Ann Donaldson', :email => 'julie-ann.donaldson@5rooms.com'},
{ :name => 'Julie Shan Hodgson', :email => 'julie@style36.co.za'},
{ :name => 'Kaitlyn de Villiers', :email => 'kaitlyn.devilliers@style36.co.za'},
{ :name => 'Katherine De Kock', :email => 'katherine.dekock@kinderelo.co.za'},
{ :name => 'Keegan Arendse', :email => 'keegan.arendse@style36.co.za'},
{ :name => 'Kelley-Anne Debeer', :email => 'kelleyann.debeers@style36.co.za'},
{ :name => 'Kim Patrick', :email => 'kim.patrick@5rooms.com'},
{ :name => 'Kurt Napoleon', :email => 'kurt.napoleon@5rooms.com'},
{ :name => 'Kyle Wedel', :email => 'kyle.wedel@aiaccelerator.com'},
{ :name => 'Larry Groenwald', :email => 'larry.groenewald@aiaccelerator.com'},
{ :name => 'Lasse Vinther', :email => 'lasse.vinther@5rooms.com'},
{ :name => 'Laura Matthews', :email => 'laura.matthews@style36.co.za'},
{ :name => 'Lauren Thomas', :email => 'lauren.thomas@aiaccelerator.com'},
{ :name => 'Lauren Grahm', :email => 'lauren@kinderelo.co.za'},
{ :name => 'Lauriaane Fourie', :email => 'lauriaane@5rooms.com'},
{ :name => 'Lawrence Jonathan Carelse', :email => 'lawrence@aiaccelerator.com'},
{ :name => 'Lee-Roy Swartz', :email => 'leeroy.swartz@5rooms.com'},
{ :name => 'Lefu Ntho', :email => 'lefu.ntho@5rooms.com'},
{ :name => 'Leigh-Ann Nel', :email => 'leighann@aiaccelerator.com'},
{ :name => 'Lina Shabangu', :email => 'lina.shabangu@aiaccelerator.com'},
{ :name => 'Linray Lavigre', :email => 'linray.lavigre@style36.co.za'},
{ :name => 'Liyah Isaacs', :email => 'liyah.isaacs@5rooms.com'},
{ :name => 'Loretta Jakubiec', :email => 'loretta.jakubiec@style36.co.za'},
{ :name => 'Ludwig Punt', :email => 'ludwig.punt@5rooms.com'},
{ :name => 'Manfred Van Nieuhuizen', :email => 'manfred@5rooms.com'},
{ :name => 'Margi Van der Westhuizen', :email => 'margi@kinderelo.co.za'},
{ :name => 'Mariam Omar', :email => 'mariam.omar@aiaccelerator.com'},
{ :name => 'Martin Vogdt', :email => 'martinv@aiaccelerator.com'},
{ :name => 'Maganathan Naidoo', :email => 'megan.naidoo@style36.co.za'},
{ :name => 'Meghan Leeson', :email => 'meghan.leeson@style36.co.za'},
{ :name => 'Meghaane Coetzee', :email => 'meghanne.coetzee@style36.co.za'},
{ :name => 'Melanie Botma', :email => 'melanie.botma@5rooms.com'},
{ :name => 'Melanie Holman', :email => 'melanie.holman@5rooms.com'},
{ :name => 'Miriam Bracht', :email => 'miriam.bracht@5rooms.com'},
{ :name => 'Nabeelah Isaacs', :email => 'nabeelah.isaacs@style36.co.za '},
{ :name => 'Naomi Freeman', :email => 'naomi.freeman@5rooms.com'},
{ :name => 'Natalie Goliath', :email => 'natalie.goliath@style36.co.za'},
{ :name => 'Natasha  Cloete', :email => 'natasha.cloete@aiaccelerator.com'},
{ :name => 'Natasha Stroud', :email => 'natasha.stroud@style36.co.za'},
{ :name => 'Nazeema Grobler', :email => 'nazeema.grobler@5rooms.com'},
{ :name => 'Nelisa Poni', :email => 'nelisa@kinderelo.co.za'},
{ :name => 'Neville Sleigh', :email => 'neville.sleigh@style36.co.za'},
{ :name => 'Nicole Lorez Groenmeyer', :email => 'nicole.groenmeyer@aiaccelerator.com'},
{ :name => 'Nigel  Hendricks', :email => 'nigel.hendricks@aiaccelerator.com'},
{ :name => 'Nikki Horsten', :email => 'nikki.horsten@style36.co.za'},
{ :name => 'Nils Korber', :email => 'nils.koerber@5rooms.com'},
{ :name => 'Nina Grindley', :email => 'nina.lieska@style36.co.za'},
{ :name => 'Nodumo Ntoni', :email => 'nodumo.ntoni@aiaccelerator.com'},
{ :name => 'Nontutuzelo Priscilla Mabumbulu', :email => 'nontutuzelo.mabumbulu@5rooms.com'},
{ :name => 'Noshaat Isaacs', :email => 'noshaat.isaacs@aiaccelerator.com'},
{ :name => 'Paul Leonard', :email => 'paul.leonard@aiaccelerator.com'},
{ :name => 'Paula Kelly', :email => 'paula.kelly@aiaccelerator.com'},
{ :name => 'Peter Phillip', :email => 'peter.phillip@aiaccelerator.com'},
{ :name => 'Phumelele Bezu', :email => 'phumi.bezu@style36.co.za'},
{ :name => 'Maria Spratley', :email => 'pia@aiaccelerator.com'},
{ :name => 'Pierre Coetzee', :email => 'pierre.coetzer@aiaccelerator.com'},
{ :name => 'Raewyn Visser', :email => 'raewyn.visser@aiaccelerator.com '},
{ :name => 'Rashid Kirabira Ssemukwano', :email => 'rashid.kirabiri@5rooms.com'},
{ :name => 'Redhaa Ariefdien', :email => 'redhaa.ariefdien@5rooms.com'},
{ :name => 'Remo Giovanni Abbondandolo', :email => 'remo@aiaccelerator.com'},
{ :name => 'Rene Walker', :email => 'rene.walker@aiaccelerator.com'},
{ :name => 'Riccardo Van Lingen', :email => 'ricardo.vanlingen@style36.co.za'},
{ :name => 'Riccardo Anrade', :email => 'riccardo.andrade@5rooms.com'},
{ :name => 'Richard Skunde', :email => 'richard.skhunde@aiaccelerator'},
{ :name => 'Ridwa Manuel', :email => 'ridwa.manuel@5rooms.com  '},
{ :name => 'Rifumo Madaka', :email => 'rifumo.mdaka@aiaccelerator.com'},
{ :name => 'Robert Mukamba', :email => 'robert.mukamba@5rooms.com'},
{ :name => 'Robyn Dippenaar', :email => 'robyn.dippenaar@style36.co.za'},
{ :name => 'Robyn Sampson', :email => 'robyn.sampson@style36.co.za'},
{ :name => 'Robynn-Mari Wilson', :email => 'robynn-mari.wilson@5rooms.com'},
{ :name => 'Romain Diaz', :email => 'romain.diaz@aiaccelerator.com'},
{ :name => 'Rudolph Nayakatwa', :email => 'rudolph.nyakatawa@style36.co.za'},
{ :name => 'Runiel Phigland', :email => 'runiel.phigeland@kinderelo.co.za'},
{ :name => 'Sachiko Okada', :email => 'sachi@style36.co.za'},
{ :name => 'Samuel Mosimane', :email => 'samuel.mosimane@5rooms.com'},
{ :name => 'Sean Weldon', :email => 'sean.weldon@5rooms.com'},
{ :name => 'Shabodeen Taliep', :email => 'shabodeen.taliep@style36.co.za '},
{ :name => 'Soletu Mazimela', :email => 'soletu.mazimela@5rooms.com'},
{ :name => 'Sonja Ludwick', :email => 'sonje.ludwick@style36.co.za'},
{ :name => 'Souzaan Rylands', :email => 'souzaan@style36.co.za'},
{ :name => 'Stephan Richards', :email => 'stephen.richards@5rooms.com'},
{ :name => 'Stuart Lewis', :email => 'stuart.lewis@style36.co.za'},
{ :name => 'Surita Douglas', :email => 'surita@5rooms.com'},
{ :name => 'Susan Searle', :email => 'susan.searle@style36.co.za'},
{ :name => 'Tahni Kelly Alexander', :email => 'tahni.alexander@5rooms.com'},
{ :name => 'Tando Guzana', :email => 'tando.guzana@style36.co.za'},
{ :name => 'Tania van der Merscht', :email => 'tania.mescht@aiaccelerator.com'},
{ :name => 'Tanya Horak', :email => 'tanya@aiaccelerator.com'},
{ :name => 'Taryn Leigh Britt Whittles', :email => 'taryn.whittles@aiaccelerator.com'},
{ :name => 'Tashreek Jacobs', :email => 'tashreek.jacobs@5rooms.com'},
{ :name => 'Tasneem Ahmed', :email => 'tasneem.ahmed@style36.co.za'},
{ :name => 'Tawanda Chimhungwe', :email => 'tawanda.chimhungwe@5rooms.com'},
{ :name => 'Tim Lycett', :email => 'tim.lycett@aiaccelerator.com'},
{ :name => 'Vivian De Vaal', :email => 'vivian.dewaal@style36.co.za'},
{ :name => 'Warren Cowley', :email => 'warren.cowley@5rooms.com'},
{ :name => 'Waseemah Theunissen', :email => 'waseemah.theunissen@5rooms.com'},
{ :name => 'Wesley Heynes', :email => 'wesley.heynes@style36.co.za '},
{ :name => 'Willem Minnaar', :email => 'willem@style36.co.za'},
{ :name => 'Mogamat Yazeed Peters', :email => 'yazeed.peters@style36.co.za'},
{ :name => 'Youmnah Valentine', :email => 'youmnah@aiaccelerator.com'},
{ :name => 'Zahlia  Manuels', :email => 'zahlia.manuels@aiaccelerator.com'},
{ :name => 'Mogamat Zayne Manuels', :email => 'zayne.manuels@style36.co.za'},
{ :name => 'Zihkona Qongqo', :email => 'zikhona.qongqo@aiaccelerator.com '},
{ :name => 'Ziyanda Klaas', :email => 'ziyanda.klaas@5rooms.com'},
{ :name => 'Zubair Noor', :email => 'zubair@aiaccelerator.com'}




]

# range for random password
range = [*'0'..'9', *'a'..'z', *'A'..'Z']

users.each do |u|
	# puts "#{u.inspect}"

	password = Array.new(8){range.sample}.join
	puts "#{u[:name]} - #{u[:email]} - #{password}"
	user = User.new(:name => u[:name], :email => u[:email], :password => password, :password_confirmation => password)
	if user.save
		puts "User #{user.id} created!"
	else 
		puts "Error #{user.errors.full_messages}"
	end
	puts "Sending welcome email"
	TransactionMailer.welcome(user, password).deliver
	puts "Email sent"
end